from FileHandler import *
import os
import subprocess
import shutil

# clean up
shutil.rmtree("./latex", ignore_errors=True)
shutil.rmtree("./html", ignore_errors=True)

# run doxygen
subprocess.call(["doxygen", "doxy_config"])

# modify latex src
texHandler = FileHandler("./latex/refman.tex")
    # change footer
texHandler.removeLine("\\fancyfoot[RE]{\\fancyplain{}{\\bfseries\\scriptsize Generated by Doxygen }}", 1)
texHandler.replaceLine("\\fancyfoot[LO]{\\fancyplain{}{\\bfseries\\scriptsize Generated by Doxygen }}",
                       "\\fancyfoot[RE]{\\fancyplain{}{\\bfseries\\scriptsize Casalino Andrea }} \n" +
                       "\\fancyfoot[LO]{\\fancyplain{}{\\bfseries\\scriptsize Casalino Andrea }}", 1)
    # put additional packages
texHandler.addAfter("%===== C O N T E N T S =====" , 
                    "\\usepackage{graphicx,color, import} \n" +
                    "\\usepackage{amssymb, amsmath}", 1)
    # put authorship
texHandler.replaceLine("{\\large Generated by Doxygen 1.8.17}\\\\",
                       "{\\large Casalino Andrea } \\\\ \n" +
                       "{\\large andrecasa91@gmail.com } \\\\", 1)
    # put additional contents
texHandler.addAfter("%--- Begin generated contents ---" , FileHandler("./additional_Sections.tex").getContent(), 1)
texHandler.reprint("./latex/refman.tex")

# generate pdf
os.chdir("latex")
subprocess.call(["pdflatex", "refman"])
subprocess.call(["makeindex", "refman.idx"])
subprocess.call(["pdflatex", "refman"])
subprocess.call(["pdflatex", "refman"])
subprocess.call(["pdflatex", "refman"])
subprocess.call(["makeindex", "refman.idx"])
subprocess.call(["pdflatex", "refman"])
os.chdir("..")

# copy generated pdf to root
shutil.copyfile("./latex/refman.pdf", "../EFG_updated.pdf")

# copy html folder to root
shutil.rmtree("../html", ignore_errors=True)
shutil.copytree("./html", "../html")

# clean up
shutil.rmtree("./html", ignore_errors=True)
shutil.rmtree("./latex", ignore_errors=True)
shutil.rmtree("__pycache__", ignore_errors=True)
